/*

 MAP_DUNGEON_R.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 8
   Tile set      : C:\gbdk\gbtd\Dungeon Tiles\Tileset_1_Map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Map_Dungeon_R_h_INCLUDE
#define __Map_Dungeon_R_h_INCLUDE

#define Map_Dungeon_RWidth 10
#define Map_Dungeon_RHeight 8
#define Map_Dungeon_RBank 0

extern const unsigned char Map_Dungeon_R[];

#endif

/* End of MAP_DUNGEON_R.H */
