/*

 TILES_DROP_HEART.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Drop_Heart_h_INCLUDE
#define __Tiles_Drop_Heart_h_INCLUDE

/* Bank of tiles. */
#define Tiles_Drop_HeartBank 0
/* Start of tile array. */
extern const unsigned char Tiles_Drop_Heart[];

#endif

/* End of TILES_DROP_HEART.H */
