/*

 TILES_SWORD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Sword_h_INCLUDE
#define __Tiles_Sword_h_INCLUDE

/* Bank of tiles. */
#define Tiles_SwordBank 0
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK2[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK3[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK4[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK5[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK6[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK7[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK8[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK9[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK10[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK11[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK12[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK13[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK14[];
/* Start of tile array. */
extern const unsigned char Tiles_SwordBLK1[];

#endif

/* End of TILES_SWORD.H */
