/*

 TILES_HIRO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Hiro_h_INCLUDE
#define __Tiles_Hiro_h_INCLUDE

/* Bank of tiles. */
#define Tiles_HiroBank 0
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK2[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK3[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK4[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK5[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK6[];
/* Start of tile array. */
extern const unsigned char Tiles_HiroBLK1[];

#endif

/* End of TILES_HIRO.H */
