/*

 TILES_HIRO_ATTACK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Hiro_Attack_h_INCLUDE
#define __Tiles_Hiro_Attack_h_INCLUDE

/* Bank of tiles. */
#define Tiles_Hiro_AttackBank 0
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK2[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK3[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK4[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK5[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK6[];
/* Start of tile array. */
extern const unsigned char Tiles_Hiro_AttackBLK1[];

#endif

/* End of TILES_HIRO_ATTACK.H */
