/*

 TILES_DROP_HEART.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char Tiles_Drop_Heart[] =
{
  0x00,0x00,0x6C,0x6C,0xBA,0xD6,0xFE,0x82,
  0xBA,0xC6,0x54,0x6C,0x28,0x38,0x10,0x10
};

/* End of TILES_DROP_HEART.C */
