/*

 TILES_EFFECT_DEATH.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Effect_Death_h_INCLUDE
#define __Tiles_Effect_Death_h_INCLUDE

/* Bank of tiles. */
#define Tiles_Effect_DeathBank 0
/* Start of tile array. */
extern const unsigned char Tiles_Effect_DeathBLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_Effect_DeathBLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_Effect_DeathBLK2[];
/* Start of tile array. */
extern const unsigned char Tiles_Effect_DeathBLK1[];

#endif

/* End of TILES_EFFECT_DEATH.H */
