/*

 TILES_BAT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 19

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Tiles_Bat_h_INCLUDE
#define __Tiles_Bat_h_INCLUDE

/* Bank of tiles. */
#define Tiles_BatBank 0
/* Start of tile array. */
extern const unsigned char Tiles_BatBLK0[];
/* Start of tile array. */
extern const unsigned char Tiles_BatBLK1[];
/* Start of tile array. */
extern const unsigned char Tiles_BatBLK2[];
/* Start of tile array. */
extern const unsigned char Tiles_BatBLK3[];
/* Start of tile array. */
extern const unsigned char Tiles_BatBLK1[];

#endif

/* End of TILES_BAT.H */
